name: Deploy to gh-pages

on:
  push:
    branches:
    - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        mkdir dist
        cd ./dist
        git config --global user.email "xeontem@gmail.com"
        git config --global user.name "Artsiom Kukharev"
        git init
        git remote add origin "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/xeontem/KungFu-Crane-game-team"
        git fetch
        git checkout gh-pages
        cd ../
        npm i
        npm run build
        cd ./dist
        git add .
        git commit -m "Github Actions Bot auto deploy"
        git push origin gh-pages
      env:
        CI: true
